version: '2'
services:
//name of service can be used to calling them
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  front-end:
    build: .
    command: npm start
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"

  back-end:
    build: .
    command: supervisor app.js
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo